hyperledger-cello/cello

.github/stale.yml, CODEOWNERS
Signed-off-by: Ry Jones <ry@linux.com>
=> Defang stalebot

README.md
Also to test the new github-based process
=> Fix the image path

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Add bug issue & pull request template.
=> [Close #32] Add bug issue & pull request template

azure-pipelines.yml, ci/check.yml
Add multi jobs support, and move make check into template.
=> [Close #37] Move make check into template

.github/ISSUE_TEMPLATE/bug_report.md
Add more context info for bug report.
=> [Close #53] Refine bug report issue template

src/agent/kubernetes-agent/src/utils/client.py, src/api-engine/requirements.txt
Change extensions/v1beta1 to apps/v1 api for deployment.
Upgrade kubernetes client api to 10.0.1.
=> [Fix #52] Fix k8s 1.16 later version not support.

src/dashboard/src/pages/Operator/Node/Node.js
=> [#54]Remove the create button in node page when the user is operator

src/dashboard/netlify.toml
Add netlify.toml under dashboard folder.
Signed-off-by: HaiTao Yue <hightallyht@gmail.com>
=> [Close #83] Fix netlify build function failed

src/dashboard/src/pages/Operator/Node/New/Fabric/ca.js, src/dashboard/src/pages/Operator/Node/Node.js, src/dashboard/src/pages/Operator/UserManagement.js, src/dashboard/src/service-worker.js
This should stop CI from complaining about code formatting
`~/cello$ prettier --write "src/**/*.js"`
was how I did it
=> Fix Prettier error

src/agent/fabric-operator/README.md
Fixes #116 Added documentation of PersistentVolume
=> Documented requirements on persistent storage

build_image/dockerhub/latest/common/api-engine/Dockerfile, build_image/dockerhub/latest/common/api-engine/entrypoint.sh, build_image/dockerhub/latest/common/api-engine/server.ini
=> Update api-engine dockerfile for dockerhub build

src/api-engine/api/routes/agent/views.py, src/api-engine/api/routes/file/views.py, src/api-engine/api/routes/node/views.py
fix #131
Signed-off-by: Haitao Yue <hightallyht@gmail.com>
=> fix(swagger): disable manual parameter for swagger doc

README-H3C.md
Signed-off-by: xieruitao-h3c <rtxie@h3c.com>
=> [Issue-123]Add readme to this branch for new users

ci/check-component.yml, ci/process-components.yml
With this pull request the build will run and test each component when
changes affect them. Otherwise, the run and test for the component
will be skipped.
Signed-off-by: Tong Li <litong01@us.ibm.com>
=> Optimize build process

src/agent/k8s/blockchain_network.py
repair a bug for add peers in couchdb mode.
=> Release 0.9.0 h3c

README-H3C.md, src/agent/k8s/blockchain_network.py
Signed-off-by: xieruitao-h3c <rtxie@h3c.com>
=> [Issue-249]blockchain_network.py line 249 SyntaxError

src/dashboard/config/router.config.js, src/dashboard/src/pages/Operator/Node/New/Fabric/ca.js, src/dashboard/src/pages/Operator/Node/New/Fabric/orderer.js, src/dashboard/src/pages/Operator/Node/New/Fabric/peer.js, src/dashboard/src/pages/Operator/Node/New/basicInfo.js, src/dashboard/src/pages/Operator/Node/New/nodeInfo.js, src/dashboard/src/pages/Operator/Node/index.js
fix #156
Signed-off-by: Haitao Yue <hightallyht@gmail.com>
=> fix: fix new node operation page can't work

.gitignore, kconfig-lib/kconfiglib.py
fix #172
Signed-off-by: Haitao Yue <hightallyht@gmail.com>
=> fix: fix .config file content can not load for kconfig

src/dashboard.py, src/modules/blockchain_network.py
=> fix healthy check

src/api-engine/api/config.py, src/api-engine/api/routes/organization/views.py
=> Organization

build_image/docker/cello-hlf/Dockerfile
* Fix python version to use python3;
* Fix the manifest-tool path with latest version;
* Other clean ups on comments.
=> Fix cello-hlf image dockerfile

src/api-engine/api/models.py, src/api-engine/api/routes/agent/serializers.py, src/api-engine/api/routes/agent/views.py, src/api-engine/api/routes/network/serializers.py, src/api-engine/api/routes/network/views.py
fix genesisblock
*Save genesisblock to database
*Agent adds update function，You can bind organizations
=> Nodecreate2

src/api-engine/api/routes/node/serializers.py, src/api-engine/api/routes/node/views.py, src/api-engine/api/routes/organization/serializers.py, src/api-engine/api/routes/organization/views.py
Node add start interface
*Node add start interface，Save the configuration file of peer to the database。
*Organization add update function
=> Nodecreate3

src/dashboard/src/locales/en-US/login.js, src/dashboard/src/locales/zh-CN/login.js, src/dashboard/src/pages/User/Login.js
Add setting password to registration page, and check whether the two passwords are the same
=> [#234]Add setting password to registration page

src/dashboard/src/pages/User/Login.js
=> [#236]Add the input organization name box to the login page

src/api-engine/api/auth.py, src/api-engine/api/models.py, src/api-engine/api/routes/agent/views.py, src/api-engine/api/routes/general/serializers.py, src/api-engine/api/routes/general/views.py, src/api-engine/api/routes/network/views.py, src/api-engine/api/routes/node/views.py, src/api-engine/api/routes/organization/views.py, src/api-engine/api/routes/user/views.py, src/api-engine/api_engine/urls.py
Add login and register interfaces, add login and register interfaces,Add token verification of interface
=> Add login and register interfaces

src/api-engine/api/lib/pki/cryptogen/cryptocfg.py, src/api-engine/api/routes/network/serializers.py, src/api-engine/api/routes/network/views.py, src/api-engine/api/routes/organization/serializers.py, src/api-engine/api/routes/organization/views.py, src/api-engine/api_engine/urls.py
Create an organization and determine the number of nodes
=> Networkcreate

src/dashboard/config/router.config.js, src/dashboard/mock/network.js, src/dashboard/src/locales/en-US.js, src/dashboard/src/locales/en-US/menu.js, src/dashboard/src/locales/en-US/operatorNetwork.js, src/dashboard/src/locales/zh-CN.js, src/dashboard/src/locales/zh-CN/menu.js, src/dashboard/src/locales/zh-CN/operatorNetwork.js, src/dashboard/src/pages/Operator/Network/Network.js, src/dashboard/src/pages/Operator/Network/styles.less, src/dashboard/src/pages/Operator/models/network.js, src/dashboard/src/services/network.js
Add network list page,show all blockchian network in this page.
=> [#224 Add networklist page]

src/api-engine/api/routes/organization/views.py
When creating an organization, you can select the number of peers and orderers。
*Create the certificate and configuration file and compress it into a zip file
=> Create organization and create node at the same time

src/api-engine/api/lib/configtxgen/configtx.py, src/api-engine/api/models.py, src/api-engine/api/routes/network/serializers.py, src/api-engine/api/routes/network/views.py, src/api-engine/api/utils/port_picker.py
create netowork and start at the same time
*create network and then start all node by turn;
=> create network and start

src/dashboard/mock/agent.js, src/dashboard/mock/network.js, src/dashboard/mock/node.js, src/dashboard/mock/organization.js, src/dashboard/mock/user.js, src/dashboard/src/services/agent.js, src/dashboard/src/services/api.js, src/dashboard/src/services/error.js, src/dashboard/src/services/network.js, src/dashboard/src/services/node.js, src/dashboard/src/services/organization.js, src/dashboard/src/services/user.js
Change the address header from /api to /api/v1
=> [#issue-258]Modify the request address of the UI

src/api-engine/api/routes/agent/serializers.py, src/api-engine/api/routes/node/serializers.py, src/api-engine/api/routes/node/views.py
failed to load swagger api definition, fixed it by removing undefined fields and serailizers.
Close #264
Signed-off-by: Yuanmao Zhu <zhu.yuanmao18@gmail.com>
=> fix #264: fix swagger api doc loading error.

src/api-engine/api/routes/general/serializers.py, src/api-engine/api/routes/general/views.py, src/api-engine/api_engine/urls.py, src/dashboard/src/services/api.js
*The user logins through the front page，and get token.
=> The user logs in through the front page

src/api-engine/api/routes/agent/views.py, src/api-engine/api/routes/general/views.py, src/api-engine/api/routes/node/views.py, src/api-engine/api/routes/user/views.py
Users can login, view agent, node, and other organizational resources；
=> Users use the front page to log in to cello

src/dashboard/src/pages/Operator/Agent/Agent.js, src/dashboard/src/pages/Operator/Agent/newAgent.js
Modify the agent through the front page，
*At present, only the name can be modified; Other parameters of the agent should not be modified.
There may be changes in the future.
*Reserve the authority of the operator role. Later, the operator will probably be deleted because it does not need to exist in baas.
=> Modify the agent through the front page

src/api-engine/api/models.py, src/api-engine/api/routes/channel/serializers.py, src/api-engine/api/routes/channel/views.py, src/api-engine/api_engine/urls.py
Implemented channel create endpoint, but did not integrate with
configtxgen yet.
Signed-off-by: Yuanmao Zhu <zhu.yuanmao18@gmail.com>
=> Channel create endpoint

src/api-engine/api/common/__init__.py, src/api-engine/api/common/response.py, src/api-engine/api/exceptions.py, src/api-engine/api/models.py, src/api-engine/api/routes/agent/views.py, src/api-engine/api/routes/general/serializers.py, src/api-engine/api/routes/general/views.py, src/api-engine/api/utils/__init__.py
*Return data in the format of {data, MSG, status}
*Add exception handling
=> Return value format

src/dashboard/src/pages/Operator/Agent/Agent.js, src/dashboard/src/pages/Operator/models/agent.js, src/dashboard/src/services/agent.js
Modify the agent management page to adapt the new API interface, including creating and updating agents.
=> [#issue-286]Modify the agent management page

src/api-engine/api/common/response.py, src/api-engine/api/routes/agent/views.py
*return value error;
*delete agent, can't find json data.
=> fix agent bug

src/api-engine/api/lib/pki/cryptogen/cryptocfg.py, src/api-engine/api/models.py, src/api-engine/api/routes/general/views.py, src/api-engine/api/routes/node/serializers.py, src/api-engine/api/routes/node/views.py
*Modify return value format
*Optimize the create, delete and list functions
*The update function has not been optimized
=> Modify node

src/dashboard/mock/agent.js, src/dashboard/mock/organization.js, src/dashboard/mock/user.js, src/dashboard/src/pages/Operator/Agent/Agent.js, src/dashboard/src/pages/Operator/models/organization.js
1.Modify the organization's mock according to the new interface
2.Modify the method of extracting organization data from agent page according to the new interface
3.Modify the organization page and extract the organization list according to the returned information of the new interface
4.Modify the user's mock login interface address
fix #issue-297
=> [#issue-297]Modify page display and mock data

src/api-engine/api/models.py, src/api-engine/api/routes/network/serializers.py, src/api-engine/api/routes/network/views.py
*Optimize return format.
*Optimize list, create function.
=> Optimize network module

src/dashboard/config/router.config.js, src/dashboard/mock/user.js, src/dashboard/src/components/Login/map.js, src/dashboard/src/locales/en-US/login.js, src/dashboard/src/locales/zh-CN/login.js, src/dashboard/src/models/login.js, src/dashboard/src/pages/Operator/Agent/Agent.js, src/dashboard/src/pages/User/Login.js
1. When registering a user, change the user name to email
2. When logging in, change the user name to email and remove the organization name
3. Modify the user role judgment and only retain two roles: "admin" and "member"
Close #300
=> [#issue-300]Modify registration, login, and user roles

src/api-engine/api/routes/network/views.py, src/api-engine/api/routes/organization/serializers.py, src/api-engine/api/routes/organization/views.py
*it take a lot of time to start node,so use threads;
*delete channel in the organization model;
=> use threads to start nodes

build_image/docker/common/api-engine/Dockerfile.in, src/api-engine/api/lib/pki/cryptogen/cryptogen.py
=> add fabric tools

src/api-engine/api/lib/peer/basicEnv.py, src/api-engine/api/lib/peer/chaincode.py
Construct the chaincode class and implement the methods of chaincode package and chaincode install
Close #issue-317
Signed-off-by: zhaoshihong <523713078@qq.com>
=> [#issue-317] cmdLineLib of chaincode operation

src/api-engine/api/lib/peer/chaincode.py, src/api-engine/api/lib/peer/channel.py
If the file has already been created. Then an exception occurs, at which point the file is not deleted, and the next time the function is called, the information continues to be written to the file, causing the user to get an exception.
Perhaps using files is not a good method;
Close #issue-319
Signed-off-by: zhaoshihong <523713078@qq.com>
=> [#issue-319] There is a risk of obtaining expired information

build_image/docker/common/api-engine/Dockerfile.in, template/node/core.yaml.bak, template/node/orderer.yaml.bak
add peer and orderer template, so we can create our own profile that depends on them;
=> add template profile

src/api-engine/api/lib/peer/chaincode.py
implement of lifecycle_query_committed && invoke function
Close #issue-332
Signed-off-by: tianxuanhong <523713078@qq.com>
=> [#issue-332] lifecycle_query_committed && invoke function

src/api-engine/api/lib/configtxgen/configtx.py, src/api-engine/api/lib/configtxgen/configtxgen.py
Refactor configtx by using a sample file and add the outputBlock flag to configtxgen cmd
=> Refactor configtx and configtxgen

bootup/docker-compose-files/docker-compose-dev.yml, src/agent/docker-rest-agent/server.py, src/api-engine/api/lib/agent/docker/handler.py
Create a docker network to connect containers of api-engine and containers of hlf nodes.
=> Create a docker network

src/api-engine/api/routes/network/views.py
Change hlf nodes names and set hlf nodes' ports then we can use fabric-tools to connect them
=> Change Fabric nodes naming 

tests/postman/test/cello-api.json
Add `cello-api.json` json file which includes some api doc of channel endpoints. 
=> Add api requests examples in postman json format.

Makefile, README.md
Rewrite the quick start part of README, so we can use this instruction to run the cello application.
=> Update quick start part of README

src/api-engine/api/lib/peer/chaincode.py
There has a bug of Call cmd, need to be fixed: Cannot find the peer binary file now.
Close #issue-#355
Signed-off-by: tianxuanhong <523713078@qq.com>
=> [#issue-355] There has a bug of Call cmd, need to be fixed

src/dashboard/mock/channel.js, src/dashboard/mock/node.js, src/dashboard/src/locales/en-US/operatorChannel.js, src/dashboard/src/locales/zh-CN/operatorChannel.js, src/dashboard/src/pages/Operator/Channel/Channel.js, src/dashboard/src/pages/Operator/Channel/styles.less, src/dashboard/src/pages/Operator/models/channel.js
Add page to create channel
Close #360
=> [#issue-360]Add page to create channel

src/api-engine/api/routes/chaincode/views.py
Realize the chain code package function. In the post request, you need to carry the zip package and MD5 value. After decompressing it to the specified path, call the peer binary tool to perform the package operation
Close #379
=> [#issue-379] realize the chain code package function

src/dashboard/src/models/login.js, src/dashboard/src/models/user.js
Modify the front-end code according to the response information of the new login interface and the verification token interface
Close #370 
=> [#issue-370]Modify front-end login module

src/dashboard/src/models/login.js, src/dashboard/src/models/user.js, src/dashboard/src/pages/Operator/Channel/Channel.js, src/dashboard/src/pages/Operator/models/channel.js
1.Modify front end channel list page
2.Modify the response judgment to create channel request
Close #373 
Signed-off-by: fengyang_sy fengyang.09186@h3c.com
=> [#issue-373]Modify front-end channel module

src/dashboard/src/models/login.js, src/dashboard/src/services/user.js, src/dashboard/src/utils/request.js
Fixed the problem that the token could not be obtained after the first login
Close #385 
=> [#issue-385]Fix the problem of getting token

Makefile, README.md, bootup/docker-compose-files/docker-compose-dev.yml, build_image/docker/common/dashboard/Dockerfile.in, build_image/docker/common/dashboard/nginx.conf
1.add command to build dashboard image
2.bootup dashboard by "make start"
Close #383 
=> [#issue-383]make dashboard image

src/api-engine/api/models.py, src/api-engine/api/routes/chaincode/serializers.py, src/api-engine/api/routes/chaincode/views.py
implement chaincode install function, url:/api/v1/chaincodes/install, and form-data body of key: chaincode_id. If you want to call this function manually, you need to query the ID of chaincode in the database first
Close #387
=> [#issue-387] implement chaincode install function

src/api-engine/api/lib/peer/chaincode.py, src/api-engine/api/routes/chaincode/views.py
implement query_installed & get_installed_package function.We can query the chaincodes info has installed in peer nodes and can get installed chaincode.
Close #389
=> [#issue-389] implement query_installed & get_installed_package function

src/api-engine/api/routes/chaincode/serializers.py, src/api-engine/api/routes/chaincode/views.py
implement lifecycle_approve_for_my_org function
Close #393
=> [#issue-393] implement lifecycle_approve_for_my_org function

src/api-engine/api/lib/configtxgen/configtx.py, src/api-engine/api/lib/peer/chaincode.py, src/api-engine/api/routes/chaincode/serializers.py, src/api-engine/api/routes/chaincode/views.py
implement commit function and modify channel config policy.
Close #402
=> [#issue-402] implement commit function and modify channel config policy.

src/api-engine/api/routes/chaincode/serializers.py, src/api-engine/api/routes/chaincode/views.py
implement chaincode list & query_committed function
Close #408
=> [#issue-408] implement chaincode list & query_committed function

src/dashboard/config/router.config.js, src/dashboard/src/locales/en-US.js, src/dashboard/src/locales/en-US/menu.js, src/dashboard/src/locales/en-US/operatorChaincode.js, src/dashboard/src/locales/zh-CN.js, src/dashboard/src/locales/zh-CN/menu.js, src/dashboard/src/locales/zh-CN/operatorChaincode.js, src/dashboard/src/pages/Operator/ChainCode/ChainCode.js, src/dashboard/src/pages/Operator/ChainCode/styles.less, src/dashboard/src/pages/Operator/models/chaincode.js, src/dashboard/src/services/chaincode.js
Add chaincode management page
Close #410
=> [#issue-410]Add chaincode management page

src/api-engine/api/routes/network/views.py, src/api-engine/api/routes/node/views.py
Correct node status so then we can perform operations based on the current node status.
=> Fix node status after calling endpoints of node and network

Makefile, bootup/docker-compose-files/docker-compose-dev.yml
Update makefile commands, so then we can clean docker containers in
different level.
* make stop
* make clean
* make deep-clean
=> Modify makefile

src/api-engine/api/lib/agent/docker/handler.py, src/api-engine/api/lib/agent/handler.py, src/api-engine/api/routes/node/views.py
Fix stop, restart and delete operations.
=> Fix node operations

src/api-engine/api/routes/node/views.py
=> Add node status field to get nodes list api response.

src/dashboard/src/locales/en-US/operatorNode.js, src/dashboard/src/locales/zh-CN/operatorNode.js, src/dashboard/src/pages/Operator/Node/index.js
Add warning when deleting nodes
Close #434
=> [#issue-434] Add warning when deleting nodes

src/dashboard/src/pages/Operator/Node/index.js
Add display node status in node list page
Close #436
=> [#issue-436]Add display node status

src/api-engine/api/common/enums.py, src/api-engine/api/models.py, src/api-engine/api/routes/network/views.py, src/api-engine/api/routes/node/views.py
Change HLF node status according to docker container's status.
=> Refine HLF node status

Makefile, bootup/docker-compose-files/docker-compose-dev.yml, src/agent/docker-rest-agent/server.py
Use docker built-in functionality to support for Multi-Platform Docker Builds.
So cello project can develop with the m1 chips.
Signed-off-by: Yuanmao Zhu <yuanmaozhu@ualberta.ca>
=> Support M1 chip development.

src/api-engine/requirements.txt
=> Remove child dependency from requirements.txt

src/dashboard/src/pages/Operator/Node/index.js
Modify node operation list, operation type
Close #457
=> [#issue-457]Modify node operation list

README.md, docs/setup/server.md
Add detailed instructions to the setup doc, add troubleshoot section for the 
potential problems and solutions.
=> Refine the setup doc

.github/workflows/docker-image.yml, azure-pipelines.yml
This only builds the images.
Disable AZP.
Signed-off-by: Ry Jones <ry@linux.com>
=> Begin transition to GitHub Actions

src/agent/kubernetes-agent/src/utils/download.py, src/api-engine/api/routes/chaincode/views.py
=> Fix : (Security) Migitate Path Traversal Bug

src/agent/kubernetes-agent/src/utils/download.py, src/api-engine/api/routes/chaincode/views.py
Reverts hyperledger/cello#455
Signed-off-by: Yuanmao Zhu [yuanmao@ualberta.ca](mailto:yuanmao@ualberta.ca)
=> Revert "Fix : (Security) Migitate Path Traversal Bug"

src/agent/kubernetes-agent/src/utils/download.py
Revert #443 
Signed-off-by: Yuanmao Zhu [yuanmao@ualberta.ca](mailto:yuanmao@ualberta.ca)
=> Revert "Fix (security) : Path Traversal Bug"

.github/workflows/check-code.yml, src/api-engine/api/lib/configtxlator/configtxlator.py, src/api-engine/api/lib/peer/channel.py, src/api-engine/api/models.py, src/api-engine/api/routes/channel/views.py, src/api-engine/api/routes/node/serializers.py, src/api-engine/api/utils/common.py, src/api-engine/tox.ini
In #472, the tox github action plugin was not configued correctly.
That results some missing code format problems in the following PRs.
This PR adds the correct configuration to tox.ini file and fixes the 
missed code format problems.
=> Fix a gh-action issue in #472

Makefile, src/api-engine/api/routes/node/views.py, src/dashboard/src/locales/en-US/form.js, src/dashboard/src/locales/en-US/operatorNode.js, src/dashboard/src/locales/zh-CN/form.js, src/dashboard/src/locales/zh-CN/operatorNode.js, src/dashboard/src/models/node.js, src/dashboard/src/pages/Operator/Node/index.js, src/dashboard/src/services/node.js
Create frontend node buttons for uploading config file and joining channel.
Signed-off-by: Xichen Pan [xichen.pan@gmail.com](mailto:xichen.pan@gmail.com)
=> Node config upload btn and Node join channel btn

src/api-engine/api/routes/channel/serializers.py
=> Only allow Application and Orderer types to update Channel Config

.github/workflows/check-code.yml, src/api-engine/api_engine/urls.py
* Bump up python version to 3.8 in github workflow
* Add token-verify endpoint back
=> Bump up python version to 3.8 in github workflow

build_image/docker/agent/docker-rest-agent/Dockerfile.in, src/agent/docker-rest-agent/requirements.txt
* Bump docker-agent python version to 3.8
* Upgrade required dependencies to the latest releases
=> Update docker agent version and dependencies

src/dashboard/src/locales/en-US/operatorChannel.js, src/dashboard/src/locales/zh-CN/operatorChannel.js, src/dashboard/src/pages/Operator/Channel/Channel.js, src/dashboard/src/pages/Operator/models/channel.js, src/dashboard/src/services/channel.js
In the channel page, add a download button to enable downloading 
channel's config file.
=> Add download btn for channel config file

src/dashboard/src/locales/zh-CN/operatorNetwork.js
Prompt message error of network deletion success, current is "删除组织成功。"
Close #509
=> [#issue-509] Prompt message error of network deletion success

src/dashboard/src/layouts/SecurityLayout.jsx, src/dashboard/src/models/login.js
Error in judging the condition of redirection
Close #513
=> [#issue-513] Error in judging the condition of redirection

src/api-engine/api/routes/channel/views.py
Check peer nodes and orderer nodes before creating channels
=> Check node status before creating channels

Makefile, Makefile.old, README.md, bootup/docker-compose-files/docker-compose.dev.yml, bootup/docker-compose-files/docker-compose.yml, build_image/docker/common/dashboard/Dockerfile.in, docs/concepts.md, docs/contributing.md, docs/requirements.txt, mkdocs.yml, scripts/master_node/build_images.sh, scripts/master_node/download_images.sh, scripts/master_node/setup.sh, scripts/worker_node/download_images.sh
* Remove unused makefile rules
* Fix `make doc` rule
* Fix `make setup-worker` and `make setup-master`
* Update readme
=> Update repo readme file and makefile

src/api-engine/api/lib/agent/handler.py, src/api-engine/api/routes/node/views.py, src/dashboard/package.json
Fixed the nested dependency version issue, mentioned in #528.
Fixed the code style issues found by Flake8.
=> Fix make command error

README.md
Signed-off-by: Yuanmao Zhu [yuanmao@ualberta.ca](mailto:yuanmao@ualberta.ca)
=> [trivial] Fix local development environment

docs/setup/server.md
add setup-troubleshoot
Operation not permitted when using Docker Desktop
=> add setup-troubleshoot

.gitignore, MAINTAINERS.md, README.md, build_image/docker/common/nginx/Dockerfile.in, docs/setup/server.md, src/api-engine/api/lib/agent/handler.py, src/api-engine/api/routes/node/views.py, src/api-engine/requirements.txt, src/dashboard/package.json, tests/dashboard/docker-compose.yml
Merge the latest code into the 1.0 branch
Signed-off-by: fengyang_sy fengyang.09186@h3c.com
=> Merge the latest code into the 1.0 branch

bootup/docker-compose-files/docker-compose.dev.yml, bootup/docker-compose-files/docker-compose.yml
make cello-api-engine depends_on cello-postgress
=> Fix docker setting

.gitignore
1. Added the Django setting to the `.gitignore`.
2. Added the cello folder to the `.gitignore`.
=> Edited the gitignore.

src/dashboard/src/pages/Agent/Agent.js, src/dashboard/src/pages/ChainCode/ChainCode.js, src/dashboard/src/pages/Channel/Channel.js, src/dashboard/src/pages/Network/Network.js, src/dashboard/src/pages/Node/index.js, src/dashboard/src/pages/Organization/Organization.js, src/dashboard/src/pages/UserManagement/UserManagement.js
Add icons before the titles of each management page
Close #565
=> [#issue-565] Add icons before the titles of each management page

src/dashboard/config/theme.js
Adjust the page navigation font size to 16
Close #563
=> [#issue-563]Adjust the page navigation font size to 16

MAINTAINERS.md
Nominate Yang Feng <fengyang.09186@h3c.com> as release mgr.
=> Add release manager

src/api-engine/api/routes/node/serializers.py
=> [ISSUE-580] Fix Swaggers API docs

src/api-engine/api/routes/node/serializers.py, src/api-engine/api/routes/node/views.py
This PR removes multiple node creation parameter from API request and use the given name + org name as the node.
=> Remove multiple node creation

src/api-engine/api/routes/chaincode/serializers.py, src/api-engine/api/routes/chaincode/views.py
Update list Chaincode API to only return currently existing values 
in database.
The returned values will be extended in the future.
=> Clean Up List CC API

src/dashboard/src/pages/ChainCode/ChainCode.js, src/dashboard/src/services/chaincode.js
Replace the API URL for uploading the chaincode with the updated URL in the front end.
=> Connected the chaincode's upload function

build_image/docker/common/dashboard/Dockerfile.in, src/api-engine/requirements.txt
=> Updated the dependencies

src/api-engine/requirements.txt
Upgrade django and DRF to solve the dependency conflict in #625 & #626
=> Upgrade django and DRF

bootup/docker-compose-files/docker-compose-dev.yml, bootup/docker-compose-files/docker-compose.dev.yml, bootup/docker-compose-files/docker-compose.yml, src/api-engine/requirements.txt
solve issue #641 : upgrade versions of postgresql, django-extensions and django-allauth.
=> upgrade postgresql to v12 and modifity requirement.txt

azure-pipelines.yml, ci/azure-pipelines.yml
The ansible-agent docker image is not used any more, and there's reported issue with it.
https://hackerone.com/reports/2791838
=> Remove the unused ansible-agent image

src/api-engine/api/lib/peer/channel.py, src/api-engine/api/routes/channel/views.py
Reference: [Peer Channel](https://hyperledger-fabric.readthedocs.io/en/latest/commands/peerchannel.html)
=> Upgrade function of peer channel fetch to HLF V2.5.10

src/dashboard/src/locales/en-US/Node.js, src/dashboard/src/locales/zh-CN/Node.js, src/dashboard/src/pages/Node/index.js
=> delete the input form of nodes' number in node creation of FE

MAINTAINERS.md
Yang Feng and Yuanmao Zhu has been contributed to the project as maintainers, and now they are not active due to other issues. So we move them to retired maintainers.
Thanks for all their contributions!
=> Retire maintainers

src/api-engine/api/lib/agent/handler.py
Closes #471 
Redefining log events for all error handling
Signed-off-by: Jaimukund Bhan [bhanjaimukund@gmail.com](mailto:bhanjaimukund@gmail.com)
=> Issue [#474] - Improving log observability

src/dashboard/src/models/chaincode.js, src/dashboard/src/pages/ChainCode/ChainCode.js, src/dashboard/src/pages/ChainCode/forms/CommitForm.js, src/dashboard/src/services/chaincode.js
=> Update the frontend component for chaincode commit

src/api-engine/api/lib/peer/chaincode.py, src/api-engine/api/routes/chaincode/serializers.py, src/api-engine/api/routes/chaincode/views.py
=> Enhance backend support for chaincode commit
