hyperledger-cello/cello

README.md
The README.md doc contains a statement indicating
that the repository is read only, which was true
before we moved to github. Now we are on the github,
that statement is no longer true. This patch removes
that statement.
=> Removed the read only header in the doc

build_image/dockerhub/latest/agent/ansible/Dockerfile
In ansible agent dockerhub file, add curl installation.
=> [Fix #39] Add curl install for ansible agent

build_image/docker/common/nginx/nginx.conf.default
static files can't find, directory mapping is wrong
should change /var/www/server/static to /var/www/static for static files mapping.
1. make start
=> In product mode, api engine docs can not find static files

src/agent/fabric-operator/README.md, src/agent/fabric-operator/deploy/operator.yaml
[CE-715]Since the fabric operator image is now officially
being placed on docker hub, we need to change the
operator deployment script to reflect that change
and modify the README.md accordingly. This patch
fixes these issues.
=> [CE-715]Fixed the fabric operator image path issue

src/agent/kubernetes-agent/src/operations/create_node.py
For k8s agent node creation, node status check need
check whether pod is not None at first.
=> [Fix #47] Fix node status check crash for k8s agent

bootup/docker-compose-files/docker-compose.yml, build_image/docker/common/nginx/nginx.conf.default
Add media url configuration in nginx.conf.
Mount media path from host for nginx server.
=> [Fix #42] Fix nginx server media url not working

bootup/docker-compose-files/docker-compose-dev.yml, bootup/docker-compose-files/docker-compose.yml, build_image/docker/common/dashboard/config-nginx.sh, build_image/docker/common/dashboard/default.conf.tmpl
Add api engine service port info into dashboard,
and replace with varbiale in default.conf.tmpl.
=> [Fix #50] Add api engine service port into dashboard

src/agent/ansible/roles/deploy_k8s/fabricsetup/templates/fabric-services.j2
When agent tried to create daemonset to monitor the node
performance, the daemonset was still using v1beta which
has been removed in k8s v1.16. This fix will move it up
to apps/v1.
=> [#80] Ansible agent fails create daemonset on k8s 1.16

src/agent/fabric-operator/agent/Dockerfile
Kubernetes Agent for dockerhub changes
Updates https://github.com/hyperledger/cello/issues/73
Signed-off-by: Manank Patni <manank321@gmail.com>
=> Update Kubernetes Agent for dockerhub

.gitreview, CODEOWNERS, MAINTAINERS.md, docs/contributing.md, docs/index.md
=> Remove Gerrit references

build_image/dockerhub/v0.9.0/user-dashboard/Dockerfile
try to fix #109 
Signed-off-by: Dixing Xu <dixingxu@gmail.com>
=> update url for downloading fabric artifacts(fix #109)

src/api-engine/api_engine/urls.py
ran into an issue with the container failing to start.
I believe its because `base_name` is deprecated and supposed to be `basename` based off this stack overflow [post](https://stackoverflow.com/questions/59733820/django-rest-framework-drf-typeerror-register-got-an-unexpected-keyword-arg)
could you please test and verify?
=> modified base_name to basename

azure-pipelines.yml, build_image/docker/agent/ansible/Dockerfile.in, build_image/docker/common/dashboard/Dockerfile.in, ci/check-license-and-docs.yml, ci/dashandapi_post.yml, ci/dashandapi_pre.yml, ci/process-components.yml
Currently we build images on Docker Hub and test
on Azure DevOps, we need to move everything over
to Azure DevOps environment and make sure we take
advantages of the parallel build to speed up the
entire process.
Signed-off-by: Tong Li <litong01@us.ibm.com>
=> Move onto Azure DevOps

src/agent/fabric-operator/deploy/crs/fabric_v1alpha1_ca_cr.yaml, src/agent/fabric-operator/deploy/crs/fabric_v1alpha1_orderer_cr.yaml, src/agent/fabric-operator/deploy/crs/fabric_v1alpha1_peer_cr.yaml, src/agent/fabric-operator/go.mod
CA node default settings has storageClass and storageSize in
the wrong place. This PR will fix that and also move the
default version of the fabric to 1.4 for ca and 2.1 for peer
and orderer.
Signed-off-by: Tong Li <litong01@us.ibm.com>
=> Fixed fabric operator default settings

src/agent/fabric-operator/pkg/controller/ca/ca_controller.go
Issue 165 stated that the ca cert were not correctly
decoded when provided to stand up a ca node. This
patch will fix that issue.
Signed-off-by: Tong Li <litong01@us.ibm.com>
=> Fixed issue report in #165

Kconfig, Makefile, bootup/docker-compose-files/docker-compose-dev.yml, bootup/docker-compose-files/docker-compose.yml, kconfig-lib/alldefconfig.py, kconfig-lib/kconfiglib.py, kconfig-lib/menuconfig.py, kconfig-lib/oldconfig.py
close #169
Signed-off-by: Haitao Yue <hightallyht@gmail.com>
=> feat: add menuconfig support for server deployment config

build_image/docker/cello-hlf/Dockerfile, build_image/docker/cello-hlf/scripts/ca_refresh.sh, build_image/docker/cello-hlf/scripts/clean_pkg.sh, build_image/docker/cello-hlf/scripts/init.sh, build_image/docker/cello-hlf/scripts/notifier.py, build_image/docker/cello-hlf/scripts/orderer_build.sh, build_image/docker/cello-hlf/scripts/peer_build.sh, build_image/docker/cello-hlf/scripts/tools_build.sh
Add hyperledger fabric image which can be used to run hyperledger fabric
nodes including peer, orderer and ca.
=> Add hyperledger fabric image

build_image/docker/cello-hlf/scripts/init.sh
When the msp or tls path exists, currently, the init.sh will merge the
parsed files into it. This may trigger peer's booting failure.
This patchset fixes the issue by cleaning the path when the
corresponding env variable exists and the target path is not empty.
=> Clean the potential existing msp and tls paths

build_image/docker/cello-hlf/scripts/update.sh, src/agent/docker-rest-agent/intergration-test/test.py, src/agent/docker-rest-agent/server.py
* add update function
* TODO: add update.sh in upstream compose files
Signed-off-by: Dixing (Dex) Xu <dixingxu@gmail.com>
=> add update function for docker agent

MAINTAINERS.md
Tong has been inactive for more than 3 months, and he will focus on
other project, without time to continue the contribution.
Thanks for his past contributions.
=> Retire maintainer Tong Li

src/api-engine/api/routes/network/views.py
It supposes to be `serializer.validated_data.get("page", 10)`
close #256 
Signed-off-by: Yuanmao Zhu <zhu.yuanmao18@gmail.com>
=> Fix #256 api-engine syntax error

src/agent/docker-rest-agent/server.py
* related to #254
* add ports options when creating docker agent
Signed-off-by: Dixing Xu <dixingxu@gmail.com>
=> add portmap for docker agent

src/api-engine/api/models.py, src/api-engine/api/routes/agent/views.py, src/dashboard/src/pages/Operator/Agent/Agent.js
Use the front page to delete the agent;
=> Use the front page to delete the agent

src/api-engine/api/models.py, src/api-engine/api/routes/channel/serializers.py, src/api-engine/api/routes/channel/views.py, src/api-engine/api_engine/urls.py
Added a manytomanyfield in channel and updated channel creation
and query endpoints.
Close #279
Signed-off-by: Yuanmao Zhu <zhu.yuanmao18@gmail.com>
=> fix #279: fix relationship between channel and organization.

src/api-engine/api/lib/peer/channel.py
Added information processing of function list and function getinfo
Close #issue-313
Signed-off-by: zhaoshihong<523713078@qq.com>
=> [#issue-313] cmdline lib function list and getinfo has no info return

src/api-engine/api/lib/peer/chaincode.py
lifecycle_query_installed will get all chaincode information installed in peer. lifecycle_get_installed_package will get all chaincode files installed in peer,
it's input is packid_id.
Close #issue-320
Signed-off-by: zhaoshihong<523713078@qq.com>
=> [#issue-320] lifecycle_query_installed&lifecycle_get_installed_package

Makefile, build_image/docker/agent/ansible/Dockerfile.in, build_image/docker/agent/docker-rest-agent/Dockerfile.in, src/agent/docker-rest-agent/pip.conf
set source of pip in docker-agent
*You can modify the pip source by yourself, and then update the pip source with PIP parameters
=> set source of pip

src/api-engine/api/routes/organization/serializers.py, src/api-engine/api/routes/organization/views.py
Remove unused channel field from OrganizationUpdateBody serializer and change org field for Node creating in org view
=> Correct the org field name and remove unused fields

Makefile
Now when run `make clean`, the built images, temp files and db files
will be cleaned. Then you can start with a fresh env.
=> Let `make clean` clean db files

src/api-engine/api/auth.py, src/api-engine/api/common/enums.py, src/api-engine/api/models.py, src/api-engine/api/routes/agent/views.py, src/api-engine/api/routes/node/views.py
There is a problem with the background user's permission. It is admin when registering and administrator when verifying the permission of some background interfaces, resulting in the failure of the interface. Uniformly modify to admin
Close #issue-365
Signed-off-by: tianxuanhong <523713078@qq.com>
=> [#issue-365] Change the administrator to admin

build_image/docker/common/dashboard/Dockerfile.in, src/api-engine/api/config.py, src/api-engine/api/models.py, src/api-engine/api/routes/chaincode/serializers.py, src/api-engine/api/routes/chaincode/views.py, src/api-engine/api_engine/urls.py
The interface of chain code upload is added. Temporarily save the chain code in the / opt / chaincode / {MD5} directory. In the future, consider making the package function in an interface?
and modified dashboard dockerfile of base image node version from 14.2.0 to 14.13.1 , to resolve the dashboard build error: 
error strip-css-comments@5.0.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "14.2.0"
error Found incompatible module.
Close #368
=> [#issue-368] chaincode files upload

src/agent/docker-rest-agent/server.py, src/api-engine/api/lib/agent/docker/handler.py
Since we are using the docker network instead, mapping ports from hosts
is no longer necessary here. I remove these lines of code in this pr.
Fix #377 
=> Remove hardcode for publishing ports of HLF nodes. 

src/api-engine/api/config.py, src/api-engine/api/routes/node/views.py
Provide an endpoint to delete a node container. Throw an error when
deleting the last orderer order.
=> Fix node delete endpoint.

src/agent/docker-rest-agent/server.py
Mapping the whole folder instead of single files.
=> Fix voulume mapping

src/api-engine/api/routes/node/views.py
Node status should appear in the response of `GET /api/v1/nodes` endpoint now.
=> Add node status field to the response Node.

MAINTAINERS.md
Yuanmao continues contributing to the Cello project after his intern for
more than 3 months. He is working mainly on the API-engine component,
and the agent. Yuanmao is also very active in proposing features and
resolving implementation issues.
Retire inactive maintainer Qiang Xu, thanks for his past contributions!
=> Nominate yuanmao as new maintainer

src/agent/kubernetes-agent/src/utils/download.py
Unsanitized input from ```r.headers``` and ```content_type = r.headers["content-type"]
extension = mimetypes.guess_extension(content_type)
file_name = "%s%s" % (uuid4().hex, extension)
target_file = os.path.join(target_dir, secure(file_name))``` resource  flows into ```open(target_file, "wb").write(r.content)```, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to write arbitrary files.
Signed-off-by: Bhaskar <dev@bhaskar.email>
=> Fix (security) : Path Traversal Bug

README.md
=> Add inclusive language statement

src/api-engine/api/routes/node/views.py
Remove node conversion because we upgraded urls field from deprecated
JSON field to django4.0 supported one.
=> Fix `dict` object has no attribute `urls` error in the get nodes endpoint

src/api-engine/api/routes/chaincode/views.py
Change `Node.objects.get()` method to `Node.objects.filter()` to support
multiple peer nodes use case.
=> Fix chaincode package failure

Makefile, src/api-engine/api/routes/agent/views.py, src/api-engine/api/routes/network/views.py
* Add logs for `ResourceNotExists` Error.
* Create a command to remove all node containers.
* Tweak `deep-clean` command so then it can clean HLF nodes as well. 
=> Improve observability on node and network creating process

.github/workflows/check-code.yml, Makefile, src/dashboard/package.json
- Create yml file to run the code check CI.
- Fix version of eslint-plugin-import to avoid a known bug in it.
- Replace `make docker` in Makefile with new commands.
=> Enable Github CI for Code Check

src/api-engine/api/routes/node/serializers.py, src/api-engine/api/routes/node/views.py, tests/postman/test/Hyperledger Cello Api Engine.postman_collection.json
Implement the api, enable querying the node's status through node_id.
=> Implement endpoint for node query

src/api-engine/api/routes/node/serializers.py, src/api-engine/api/routes/node/views.py, tests/postman/test/Hyperledger Cello Api Engine.postman_collection.json
Enable to get config file through the api:
http://127.0.0.1:8080/api/v1/nodes/:node_id/config
A peer_config.zip or orderer_config.zip file will be returned.
=> Implement API to get node config file

src/api-engine/api/routes/node/views.py, tests/postman/test/Hyperledger Cello Api Engine.postman_collection.json
Enable to post and update config file through the api:
http://127.0.0.1:8080/api/v1/nodes/:node_id/config
orderer.yaml or core.yaml can be uploaded.
The corresponding yaml, zip files and database field will be updated.
=> Implement API to upload node config file

src/dashboard/src/pages/Operator/Node/index.js, src/dashboard/src/services/node.js
1. Change the quantity parameter to a number
2. The action parameter is passed through the message body
Close #487
=> [#issue-487]Modify the request to create a node

src/api-engine/api/routes/node/views.py, src/dashboard/src/locales/en-US/form.js, src/dashboard/src/locales/en-US/operatorNode.js, src/dashboard/src/locales/zh-CN/form.js, src/dashboard/src/locales/zh-CN/operatorNode.js, src/dashboard/src/models/node.js, src/dashboard/src/pages/Operator/Node/index.js, src/dashboard/src/services/node.js
Implement the frontend node config download button.
Call backend api to download the node config file.
=> Implement node config download btn

src/agent/docker-rest-agent/requirements.txt
Update docker-rest-agent's dependency list by adding greenlet==1.1.3.
The gevent with a version lower than 20.9.0 will have difficulty working
with greenlet v2 or higher. If no greenlet version is specified, v2 or higher
will be installed automatically, which will crush gevent.
See [StackOverflow](https://stackoverflow.com/questions/34314222/gevent-not-valid-running-docker-registry) and [GitHub Issue](https://github.com/python-greenlet/greenlet/issues/178) for details.
=> Update docker-rest-agent Dep

src/api-engine/api/routes/general/serializers.py, src/api-engine/api/routes/general/views.py, src/api-engine/api_engine/urls.py
Example response 
```
{
"data": {
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcwNjk5Njg0LCJpYXQiOjE2NzA2OTkzODQsImp0aSI6ImY1ZDc1MjUyMWJjNzQyMTVhOTQ5OTY0NWRhOTY3MmE0IiwidXNlcl9pZCI6ImEzODc4MDQwLTQ2MDItNDdlMy05YWE1LTYyYjI2OWMzN2VkOCJ9.W3dsf987YfX6c6yhaVssQF6MHxoBc6vF4HCNn8nS3Rw",
"user": {
"id": "a3878040-4602-47e3-9aa5-62b269c37ed8",
"username": "foo2@email.com",
"role": "admin",
"organization": {
"id": "142fb71a-ed52-4972-94ff-9c6b87f729d1",
"name": "org2.cello.com"
}
}
},
"msg": null,
"status": "successful"
}
```
=> Add token and user feilds to the response in token-verify endpoint

src/api-engine/api_engine/settings.py.example
The token would expire in 30 seconds originally if no request is sent from frontend.
Set the expiration time to 60 mins now.
=> Extend token expire duration

src/dashboard/src/pages/Operator/Channel/Channel.js
Channel page has a button to delete one channel. But we are going 
to implement this feature in the next release. So remove the frontend 
button for now.
=> Remove Delete Btn on Channel Page

Makefile
If current arch is arm64, use docker platform linux/amd64, 
still use linux/$(ARCH) platform for all other arches.
=> Fix m1 Support Issue in #521

build_image/docker/common/nginx/Dockerfile.in
Old Nginx docker image has compatibility issues with current Debian package manager. 
Therefore upgrade the image to the latest version. Fix [CI build failure](https://github.com/hyperledger/cello/actions/runs/4813462766/jobs/8570022172#step:3:709).
=> Upgrade Nginx Docker Image

tests/dashboard/docker-compose.yml
Based on the discussion in #536, upgrade the node image 
used by FE test to 14.17.
=> Upgrade FE test image

MAINTAINERS.md
Xichen Pan was the intern student last year, he is actively contributing into the project in terms of code, features, and bug fixes.
After his intern program, he continues to contribute to the project as an individual developer for more than half a year.
I believe the nomination will help the project move on more efficiently.
=> Nominate Xichen Pan as maintainer

src/dashboard/src/components/StandardTable/index.js
Add a prop option in StandardTable component to disable the
row selection in the table.
This is to simplify the table UI and will be used for some tables
of chaincode's sub-page.
To disable the selection, add a `disableSelect` prop to the Stand-
ardTable component.
=> Add option to disable table row selection

src/dashboard/src/pages/ChainCode/ChainCode.js, src/dashboard/src/pages/ChainCode/forms/ApproveForm.js
1. Added the approve form.
2. Checked the code style.
=> Added the approve form.

src/api-engine/requirements.txt
Bump MarkupSafe to solve the dependency conflict in #591.
=> Bump MarkupSafe from 1.1.1 to 2.0.1 in api-engine

src/api-engine/requirements.txt, src/dashboard/src/utils/request.js
Add the API response error message in the frontend notification box.
For #593 
=> Add error msg in notification

src/api-engine/api/config.py
I got this error when uploading the chaincode: ```[Error 13] Permission denied: '/opt/chaincode'```
I resolved this by changing ```FABRIC_CHAINCODE_STORE = "/opt/chaincode"``` to ```FABRIC_CHAINCODE_STORE = "/opt/cello/chaincode"``` in the ```config.py``` file.
=> Resolved the permission issue for uploading chaincode

src/api-engine/api/routes/chaincode/views.py
Calculated the sha256 value of the chaincode file and combined it with the label to get the ```package_id```.
=> Manually calculate the package id

src/dashboard/src/pages/ChainCode/ChainCode.js
The chaincode's ```package_id``` and ```description``` are correctly displayed now.
=> Fixed the chaincode information display issue

Makefile, build_image/docker/cello-hlf/Dockerfile, build_image/docker/common/api-engine/Dockerfile.in, build_image/docker/common/dashboard/Dockerfile.in, src/dashboard/package.json
build fabric2.5.9 image using local dockerfile (path: build_image/docker/cello-hlf/Dockerfile).
=> Docker image for HLF v2.5 (latest is v2.5.9): update all required images

src/api-engine/api/lib/configtxgen/configtxgen.py, src/api-engine/api/routes/channel/views.py, src/api-engine/api/routes/network/views.py
1. According to the latest [Configtxgen-Usage](https://hyperledger-fabric.readthedocs.io/en/latest/commands/configtxgen.html), "channeltx" function has been deprecated, which should be replaced by "genesis" function from _<src/api-engine/api/lib/configtxgen/configtxgen.py>_
2. Since the system channel is no longer supported (a system channel genesis block is unnecessary before creating a orderer service), delete the operations of configtx and configtxgen in the create func from _<src/api-engine/api/routes/network/views.py>._
3. Only perform genesis block creation once in channel's create function (configtxgen.genesis) from _<src/api-engine/api/routes/channel/views.py> ._
=> upgrade configtxgen to v2.5.9

build_image/docker/cello-hlf/scripts/init.sh, src/agent/docker-rest-agent/server.py, src/api-engine/api/lib/agent/docker/handler.py, src/api-engine/api/routes/network/views.py, src/api-engine/api/routes/node/views.py, src/api-engine/api/routes/organization/views.py
As HLFv2.5.9 [Channel Creation](https://hyperledger-fabric.readthedocs.io/en/latest/create_channel/create_channel_participation.html), system channels are no longer supported, which means the creation of orderer service container no longer require system channel genesis block.
=> Remove operations related to system channel genesis block creation before creating orderer service

build_image/docker/cello-hlf/Dockerfile, src/dashboard/lambda/mock/matchMock.js, src/dashboard/package.json, src/dashboard/src/components/PageHeaderWrapper/breadcrumb.js, src/dashboard/src/components/SiderMenu/SiderMenuUtils.js, src/dashboard/src/pages/Authorized.js, src/dashboard/src/utils/getPageTitle.js
=> fix bugs of upgrading path-to-regexp to v8.2.0

src/agent/docker-rest-agent/server.py, src/api-engine/api/routes/node/views.py, src/api-engine/api/utils/common.py, src/api-engine/requirements.txt
Refer to [fabric-samples/test-network](https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/compose-test-net.yaml), add and update environment variables.
=> update environment variables for nodes

src/api-engine/api/lib/configtxgen/configtx.py, src/api-engine/api/lib/configtxgen/configtxgen.py, src/api-engine/api/lib/peer/channel.py, src/api-engine/api/lib/pki/cryptogen/cryptocfg.py, src/api-engine/api/lib/pki/cryptogen/cryptogen.py, src/api-engine/api/routes/channel/views.py
1. Split the `create` function in ChannelViewSet into smaller functions for debugging.
2. Add polling mechanism for `peer channel fetch` to access the block multiple times from CLI.
=> fix issue#650 of channel fetch error

src/dashboard/src/pages/ChainCode/forms/ApproveForm.js, tests/dashboard/docker-compose.yml
=> Fix the bug that ApproveForm component in dashboard does not display the selection box of channel.

MAINTAINERS.md
Haibo Yang is one of the intern students in the year 2024. He continues to contribute to the project for more than 3 months after his internship. According to the maintainer rules, we would like to nominate him as a new maintainer.
=> Nominate Haibo Yang as new maintainer

Makefile
Closes #474 
Updated the Makefile by modifying the code to filter docker images, pruning dangling images, separating 'check' commands, and rearranging a few commands to follow alphabetical order.
Signed-off-by: Jaimukund Bhan <bhanjaimukund@gmail.com>
=> Issue-#474 Clean Makefile

src/dashboard/src/pages/ChainCode/ChainCode.js, src/dashboard/src/pages/Channel/Channel.js, src/dashboard/src/pages/Network/Network.js
Currently, users can't select multiple rows on network, channel, and chaincode pages because the classes don't implement the `handleSelectRows` function.
This commit provides the necessary implementations to those classes.
=> Create handleSelectRows implementations

src/api-engine/api/routes/node/views.py
Users couldn't remove an orderer once it had been added to a network. This creates a deadlock an invalid orderer could never be removed. This commit fixes this by allow users to remove the orderer once the network is None.
Fixes #690
=> Allow orderers to be removed when the organization network is None

src/dashboard/src/utils/request.js
Users don't have to know the URI details. Such behaviors provide bad UX for confusing people.
=> Stop showing api URL on UI for errors

src/dashboard/src/utils/request.js
Originally there were two identical request interceptors, both adding the JWT token header except for login and register requests.
However, umi-request's interceptors chain supports async functions naturally, and the Promise returned by the first interceptor is properly handled without needing a second interceptor to process it.
Therefore, the second interceptor is redundant and can be safely removed without affecting functionality, simplifying the codebase.
=> Remove redundant request interceptor
